name: CI

on:
  pull_request:
    paths:
      - '**/*.java'
      - '**/build.gradle*'
      - 'website/**'
      - 'docs/**'
    branches: [ main ]
  push:
    paths:
      - '**/*.java'
      - '**/build.gradle*'
      - 'website/**'
      - 'docs/**'
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests (ubuntu-jdk${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '21' ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Run tests
        run: ./gradlew --no-daemon clean test

      - name: Upload test reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-jdk${{ matrix.java }}
          path: |
            **/build/reports/tests/test
            **/build/test-results/test
